### ISSUE TITLE
Kernel dies when triggering auto-complete and Intellisense does not work.

### ISSUE THREAD

**Issue by schmohlio** [fsprojects/IfSharp#42]
Hello and thanks in advance!

I'm running Windows 8.1 Pro x64 in Parallels VM and recently installed IfSharp. It looks really great, and I'm able to execute code and generate graphs. 

Issue is that Intellisense does not work, and when i hit shift + tab to trigger auto-complete, the kernel dies. Below is my log - after the 2nd `open system` is when i hit <shift>.<tab> Anyone have any ideas?

As an aside,  I'm rather new to windows, but when I execute `.\ifsharp.exe --install` from Powershell I get ifsharp program crash errors, including a `..\--install` file not found... 

```
2015-07-17 13:00:39 - --> Added 'C:\Program Files\BayardRock\IFSharp' to library include path
2015-07-17 13:00:39 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\IfSharp.Kernel.dll' (file may be locked by F# Interactive process)
2015-07-17 13:00:39 - --> Referenced 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll' (file may be locked by F# Interactive process)
2015-07-17 13:00:39 - --> Referenced 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.DataVisualization.dll' (file may be locked by F# Interactive process)
2015-07-17 13:00:39 - --> Referenced 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\FSharp.Data.TypeProviders.dll' (file may be locked by F# Interactive process)
2015-07-17 13:00:39 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\FSharp.Charting.dll' (file may be locked by F# Interactive process)
2015-07-17 13:00:39 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\fszmq.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:02 - open System
2015-07-17 13:01:09 - open System
2015-07-17 13:01:13 - ArgumentNullExceptionValue cannot be null.
2015-07-17 13:01:13 - Parameter name: value
2015-07-17 13:01:13 -    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2015-07-17 13:01:13 -    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2015-07-17 13:01:13 -    at IfSharp.Kernel.IfSharpKernel.completeRequest(KernelMessage msg, CompleteRequest content)
2015-07-17 13:01:13 -    at IfSharp.Kernel.IfSharpKernel.doShell()
2015-07-17 13:01:17 - ArgumentNullExceptionValue cannot be null.
2015-07-17 13:01:17 - Parameter name: value
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.completeRequest(KernelMessage msg, CompleteRequest content)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.doShell()
2015-07-17 13:01:17 - ArgumentNullExceptionValue cannot be null.
2015-07-17 13:01:17 - Parameter name: value
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.completeRequest(KernelMessage msg, CompleteRequest content)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.doShell()
2015-07-17 13:01:17 - ArgumentNullExceptionValue cannot be null.
2015-07-17 13:01:17 - Parameter name: value
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.completeRequest(KernelMessage msg, CompleteRequest content)
2015-07-17 13:01:17 -    at IfSharp.Kernel.IfSharpKernel.doShell()
2015-07-17 13:01:21 - // include directory, this will be replaced by the kernel
2015-07-17 13:01:21 - #I "C:\\Program Files\\BayardRock\\IFSharp"
2015-07-17 13:01:21 - // load base dlls
2015-07-17 13:01:21 - #r "IfSharp.Kernel.dll"
2015-07-17 13:01:21 - #r "System.Data.dll"
2015-07-17 13:01:21 - #r "System.Windows.Forms.DataVisualization.dll"
2015-07-17 13:01:21 - #r "FSharp.Data.TypeProviders.dll"
2015-07-17 13:01:21 - #r "FSharp.Charting.dll"
2015-07-17 13:01:21 - #r "fszmq.dll"
2015-07-17 13:01:21 - // open the global functions and methods
2015-07-17 13:01:21 - open FSharp.Charting
2015-07-17 13:01:21 - open IfSharp.Kernel
2015-07-17 13:01:21 - open IfSharp.Kernel.Globals
2015-07-17 13:01:24 - F# Interactive for F# 3.1 (private)
2015-07-17 13:01:24 - Freely distributed under the Apache 2.0 Open Source License
2015-07-17 13:01:24 - For help type #help;;
2015-07-17 13:01:24 - > 
2015-07-17 13:01:24 - --> Added 'C:\Program Files\BayardRock\IFSharp' to library include path
2015-07-17 13:01:24 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\IfSharp.Kernel.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:24 - --> Referenced 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Data.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:24 - --> Referenced 'C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.DataVisualization.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:24 - --> Referenced 'C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.3.0.0\Type Providers\FSharp.Data.TypeProviders.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:24 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\FSharp.Charting.dll' (file may be locked by F# Interactive process)
2015-07-17 13:01:24 - --> Referenced 'C:\Program Files\BayardRock\IFSharp\fszmq.dll' (file may be locked by F# Interactive process)
```

**Comment by schmohlio** [comment]
also I should note that IfSharp installed within my C:\Program Files dir -- not sure if that makes sense for refrences.

**Comment by cgravill** [comment]
Hi, we've made several improvements to the install process and resilience of loading intellisense. If you get a chance please try the latest on the Jupyter branch:
https://github.com/fsprojects/IfSharp/tree/jupyter

There are also instructions for running on Mac and Linux now if that's a more familiar environment.

If it's still giving issues reopen and let us know.
