### ISSUE TITLE
ifsharp.exe --install got strange FileNotFoundException on Windows

### ISSUE THREAD

**Issue by davidshen84** [fsprojects/IfSharp#49]
My environment is:

- Windows 7 64bit
- Up to date .Net environment

        C:\Program Files\BayardRock\IFSharp>ifsharp.exe --install

        Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Pr
        ogram Files\BayardRock\IFSharp\--install'.
           at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
           at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
        nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions o
        ptions, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
        n useLongPath, Boolean checkHost)
           at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
        FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
        bFromProxy, Boolean useLongPath, Boolean checkHost)
           at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detec
        tEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
           at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean
         checkHost)
           at IfSharp.Kernel.App.Start$cont@227(String[] args, Unit unitVar)
           at IfSharpConsole.Program.Main(String[] args)

**Comment by simra** [comment]
Try running ifsharp.exe on its own (no --install argument).  According to the current code installation is triggered when there are no arguments or when there is no existing setup.

**Comment by cgravill** [comment]
We've made several improvements to the install process. Please do try without the argument. There are are additional instructions on the Jupyter branch:
https://github.com/fsprojects/IfSharp/tree/jupyter

If there are still issues feel free to re-open.
