### ISSUE TITLE
Unsupported messageType: comm_info_request on document creation/opening

### ISSUE THREAD

**Issue by Lanayx** [fsprojects/IfSharp#95]
I'm getting this error any time I'm creating or opening the IFSharp notebook. After restart kernel works properly, except Nuget doesn't work for any package (for example NuGet error: Unable to find package 'Newtonsoft.Json'), not sure if these two issues are connected. Windows 10, v3.0.0-alpha3

```
Unhandled Exception: System.Exception: Unsupported messageType: comm_info_request
   at IfSharp.Kernel.ShellMessages.Deserialize(String messageType, String messageJson) in E:\dev\IfSharp\src\IfSharp.Kernel\ShellMessages.fs:line 564
   at IfSharp.Kernel.IfSharpKernel.recvMessage(NetMQSocket socket) in E:\dev\IfSharp\src\IfSharp.Kernel\Kernel.fs:line 130
   at IfSharp.Kernel.IfSharpKernel.doShell() in E:\dev\IfSharp\src\IfSharp.Kernel\Kernel.fs:line 481
   at <StartupCode$IfSharp-Kernel>.$Kernel.StartAsync@535.Invoke(Unit unitVar) in E:\dev\IfSharp\src\IfSharp.Kernel\Kernel.fs:line 535
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1268-1.Invoke(ExceptionDispatchInfo edi)
   at <StartupCode$FSharp-Core>.$Control.loop@430-54(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@516-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by cdrnet** [comment]
Related: https://github.com/jupyter/jupyter_client/pull/34

Maybe change the issue title to "Unsupported messageType: comm_info_request"

**Comment by cgravill** [comment]
I've just confirmed this error starts between Jupyter 4.1 and Jupyter 4.2

@sylvanc added support for the message with #97 which fixes the issue. I've uploaded a new pre-release: [v3.0.0-alpha4](https://github.com/fsprojects/IfSharp/releases/download/v3.0.0-alpha4/IfSharp.v3.0.0-alpha4.zip)

I updated the documentation to say we now support Jupyter 4.2 and did some minimal tests. Please do report any further issues you see with this.

**Comment by sylvanc** [comment]
Thanks @cgravill !
